# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    paths: 
      - 'Project4/Unit-test/**'
  pull_request:
    paths: 
      - 'Project4/Unit-test/**'

defaults:
  run:
    working-directory: Project4/Unit-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # setup Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    # Setup gcloud CLI
    - name: Google SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '317.0.0'
        project_id:  ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
  
    - name: Use gcloud CLI
      run: gcloud info
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Iv flake8 requests Cython matplotlib-terminal google-cloud-core==1.4.2 google-cloud-language==1.3.0 google-cloud-storage==1.31.2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Base test of test.py
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      run: |
        pytest   
        
